# Alacritty Configuration - Theme: Nord Dark
# Colors can be overridden by deadcode theme system

[general]
live_config_reload = true

[window]
opacity = 0.95
padding.x = 12
padding.y = 12
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 12.0

[cursor]
style.shape = "Block"
style.blinking = "On"

# Nord Color Scheme
[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"
dim_foreground = "#A5AAAF"
bright_foreground = "#ECEFF4"

[colors.cursor]
text = "#2E3440"
cursor = "#D8DEE9"

[colors.vi_mode_cursor]
text = "#2E3440"
cursor = "#D8DEE9"

[colors.selection]
text = "CellForeground"
background = "#4C566A"

[colors.search.matches]
foreground = "#2E3440"
background = "#88C0D0"

[colors.search.focused_match]
foreground = "#2E3440"
background = "#5E81AC"

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

[colors.dim]
black = "#373E4D"
red = "#94545D"
green = "#809575"
yellow = "#B29E75"
blue = "#68809A"
magenta = "#8C738C"
cyan = "#6D96A5"
white = "#AEB3BB"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
