
[[keyboard.bindings]]
chars = "\u001B\r"
key = "Return"
mods = "Shift"

[general]
live_config_reload = true

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.cursor]
cursor = "#D8DEE9"
text = "#2E3440"

[colors.dim]
black = "#373E4D"
blue = "#68809A"
cyan = "#6D96A5"
green = "#809575"
magenta = "#8C738C"
red = "#94545D"
white = "#AEB3BB"
yellow = "#B29E75"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
bright_foreground = "#ECEFF4"
dim_foreground = "#A5AAAF"
foreground = "#D8DEE9"

[colors.search.focused_match]
background = "#5E81AC"
foreground = "#2E3440"

[colors.search.matches]
background = "#88C0D0"
foreground = "#2E3440"

[colors.selection]
background = "#4C566A"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#D8DEE9"
text = "#2E3440"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
opacity = 0.95

[window.padding]
x = 10
y = 10

[keyboard]
